/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminStatsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    topic?: string;
                    difficulty?: components["schemas"]["Difficulty"];
                    search?: string;
                    active?: boolean;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedResultOfAdminQuestionDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminQuestionInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminQuestionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminQuestionDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminQuestionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminQuestionDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTopicInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTopicInput"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{slug}/subtopics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSubtopicInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminRoadmapInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roadmaps/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminRoadmapInput"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roadmaps/{slug}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminStepInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/steps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminStepInput"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedResultOfAdminUserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummaryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in. Web uses useCookies=true (HttpOnly cookie); mobile/desktop receive bearer + refresh tokens */
        post: {
            parameters: {
                query?: {
                    useCookies?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out (clears the cookie and invalidates refresh tokens) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a password reset email. Always returns 202 to avoid account enumeration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the password using the code from the email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External login providers and whether they are enabled */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthProviderDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a practice session (Practice, Challenge, Random, Adaptive or a roadmap step) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartPracticeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeSessionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeSessionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/sessions/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade an answer: returns feedback, explanation, reference, XP, levels, streak and roadmap progress */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAnswerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnswerResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyChallengeStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-challenge/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeSessionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnalyticsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboards/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global, Weekly, Monthly or Topic leaderboard */
        get: {
            parameters: {
                query?: {
                    topic?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    scope: components["schemas"]["LeaderboardScope"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AchievementDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search topics, subtopics and roadmaps */
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResultDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationListDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps/{slug}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrol in a roadmap (fails with 403 while prerequisites are not met) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge tree: topics, subtopics and question counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummaryDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home dashboard: stats, continue learning, current roadmap, recommendations, daily challenge */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/topic-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicProgressDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile with topic levels, achievements, roadmap progress and activity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            tokenType?: null | string;
            accessToken: string;
            /** Format: int64 */
            expiresIn: number;
            refreshToken: string;
        };
        AchievementDto: {
            code: string;
            name: string;
            description: string;
            category: string;
            icon: string;
            tier: string;
            /** Format: int32 */
            xpReward: number;
            unlocked: boolean;
            /** Format: date-time */
            unlockedAt: null | string;
        };
        AdminOptionDto: {
            /** Format: uuid */
            id: string;
            text: string;
            isCorrect: boolean;
            /** Format: int32 */
            displayOrder: number;
        };
        AdminOptionInput: {
            text: string;
            isCorrect: boolean;
        };
        AdminQuestionDto: {
            /** Format: uuid */
            id: string;
            externalKey: null | string;
            topicSlug: string;
            subtopicSlug: string;
            difficulty: components["schemas"]["Difficulty"];
            questionType: components["schemas"]["QuestionType"];
            title: string;
            questionText: string;
            explanation: string;
            referenceUrl: string;
            /** Format: int32 */
            xpReward: number;
            isActive: boolean;
            /** Format: date-time */
            updatedAt: string;
            options: components["schemas"]["AdminOptionDto"][];
        };
        AdminQuestionInput: {
            topicSlug: string;
            subtopicSlug: string;
            difficulty: components["schemas"]["Difficulty"];
            title: string;
            questionText: string;
            explanation: string;
            referenceUrl: string;
            /** Format: int32 */
            xpReward: null | number;
            isActive: boolean;
            options: components["schemas"]["AdminOptionInput"][];
        };
        AdminRoadmapInput: {
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: components["schemas"]["RoadmapDifficulty"];
            /** Format: int32 */
            estimatedHours: number;
            icon: string;
            isPublished: boolean;
            /** Format: int32 */
            xpReward: number;
        };
        AdminStatsDto: {
            /** Format: int32 */
            users: number;
            /** Format: int32 */
            topics: number;
            /** Format: int32 */
            subtopics: number;
            /** Format: int32 */
            questions: number;
            /** Format: int32 */
            activeQuestions: number;
            /** Format: int32 */
            roadmaps: number;
            /** Format: int32 */
            steps: number;
            /** Format: int32 */
            attempts: number;
        };
        AdminStepInput: {
            /** Format: uuid */
            moduleId: null | string;
            newModuleTitle: null | string;
            title: string;
            description: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Format: int32 */
            estimatedMinutes: number;
            topicSlug: string;
            subtopicSlug: null | string;
            /** Format: int32 */
            minimumQuestions: number;
            /** Format: int32 */
            minimumAccuracy: number;
            /** Format: int32 */
            xpReward: number;
            /** Format: int32 */
            order: null | number;
        };
        AdminSubtopicInput: {
            slug: string;
            name: string;
        };
        AdminTopicInput: {
            slug: string;
            name: string;
            description: string;
            category: string;
            icon: string;
            /** @default true */
            isActive: boolean;
        };
        AdminUserDto: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            email: string;
            /** Format: int32 */
            level: number;
            /** Format: int64 */
            xp: number;
            /** Format: int32 */
            questionsAnswered: number;
            /** Format: double */
            accuracy: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt: null | string;
        };
        AnalyticsDto: {
            /** Format: int32 */
            days: number;
            /** Format: int32 */
            totalQuestions: number;
            /** Format: int32 */
            totalCorrect: number;
            /** Format: double */
            globalAccuracy: number;
            /** Format: int32 */
            studySeconds: number;
            /** Format: int64 */
            xpEarnedInPeriod: number;
            /** Format: int32 */
            currentStreak: number;
            /** Format: int32 */
            longestStreak: number;
            /** Format: double */
            xpLast7Days: number;
            /** Format: double */
            xpPrevious7Days: number;
            /** Format: double */
            velocityChangePercent: number;
            byDifficulty: components["schemas"]["DifficultyBreakdownDto"][];
            byTopic: components["schemas"]["TopicAccuracyDto"][];
            bySubtopic: components["schemas"]["SubtopicAccuracyDto"][];
            daily: components["schemas"]["DailyActivityDto"][];
            strongestTopics: components["schemas"]["TopicAccuracyDto"][];
            weakestTopics: components["schemas"]["TopicAccuracyDto"][];
        };
        AnswerFeedbackDto: {
            /** Format: uuid */
            selectedOptionId: string;
            /** Format: uuid */
            correctOptionId: string;
            isCorrect: boolean;
            explanation: string;
            referenceUrl: string;
            /** Format: int32 */
            xpEarned: number;
        };
        AnswerResultDto: {
            feedback: components["schemas"]["AnswerFeedbackDto"];
            /** Format: int32 */
            bonusXp: number;
            /** Format: int64 */
            totalXp: number;
            level: components["schemas"]["LevelDto"];
            leveledUp: boolean;
            topicSlug: string;
            /** Format: int32 */
            topicLevel: number;
            /** Format: int64 */
            topicXp: number;
            topicLeveledUp: boolean;
            /** Format: int32 */
            currentStreak: number;
            streakIncreased: boolean;
            /** Format: int32 */
            dailyChallengeBonusXp: number;
            session: components["schemas"]["SessionProgressDto"];
            completedSteps: components["schemas"]["CompletedStepDto"][];
        };
        AuthProviderDto: {
            name: string;
            displayName: string;
            enabled: boolean;
            featured: boolean;
        };
        CompletedStepDto: {
            /** Format: uuid */
            roadmapId: string;
            roadmapName: string;
            /** Format: uuid */
            stepId: string;
            stepTitle: string;
            /** Format: int32 */
            xpEarned: number;
            moduleCompleted: boolean;
            roadmapCompleted: boolean;
        };
        DailyActivityDto: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            questions: number;
            /** Format: int32 */
            correct: number;
            /** Format: int32 */
            xpEarned: number;
            /** Format: int32 */
            studySeconds: number;
        };
        DailyChallengeStatusDto: {
            /** Format: date */
            date: string;
            completed: boolean;
            /** Format: uuid */
            sessionId: null | string;
            /** Format: int32 */
            questionsCount: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: int32 */
            correctCount: number;
            /** Format: int32 */
            bonusXp: number;
        };
        DashboardDto: {
            user: components["schemas"]["UserSummaryDto"];
            continueLearning: components["schemas"]["TopicProgressDto"][];
            currentRoadmap: null | components["schemas"]["RoadmapProgressSummaryDto"];
            currentRoadmapSteps: components["schemas"]["RoadmapStepDto"][];
            recommended: components["schemas"]["RecommendationDto"][];
            dailyChallenge: components["schemas"]["DailyChallengeStatusDto"];
            recentAchievements: components["schemas"]["AchievementDto"][];
            /** Format: int32 */
            unreadNotifications: number;
        };
        /** @enum {unknown} */
        Difficulty: "Easy" | "Medium" | "Hard" | "Expert";
        DifficultyBreakdownDto: {
            difficulty: string;
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: double */
            accuracy: number;
        };
        DifficultyCountsDto: {
            /** Format: int32 */
            easy: number;
            /** Format: int32 */
            medium: number;
            /** Format: int32 */
            hard: number;
            /** Format: int32 */
            expert: number;
            /** Format: int32 */
            total?: number;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        IdResponse: {
            /** Format: uuid */
            id: string;
        };
        LeaderboardDto: {
            scope: components["schemas"]["LeaderboardScope"];
            topicSlug: null | string;
            /** Format: date-time */
            periodStart: null | string;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            entries: components["schemas"]["LeaderboardEntryDto"][];
            me: null | components["schemas"]["LeaderboardEntryDto"];
        };
        LeaderboardEntryDto: {
            /** Format: int32 */
            rank: number;
            /** Format: uuid */
            userId: string;
            username: string;
            displayName: string;
            avatarUrl: null | string;
            /** Format: int32 */
            level: number;
            /** Format: int64 */
            xp: number;
            /** Format: int32 */
            questions: number;
            /** Format: double */
            accuracy: number;
        };
        /** @enum {unknown} */
        LeaderboardScope: "Global" | "Weekly" | "Monthly" | "Topic";
        LevelDto: {
            /** Format: int32 */
            level: number;
            /** Format: int64 */
            totalXp: number;
            /** Format: int64 */
            xpIntoLevel: number;
            /** Format: int64 */
            xpForThisLevel: number;
            /** Format: int64 */
            xpToNextLevel: number;
            /** Format: double */
            progressPercent: number;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        NotificationDto: {
            /** Format: uuid */
            id: string;
            type: string;
            title: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            isRead: boolean;
        };
        NotificationListDto: {
            /** Format: int32 */
            unreadCount: number;
            items: components["schemas"]["NotificationDto"][];
        };
        OptionDto: {
            /** Format: uuid */
            id: string;
            text: string;
        };
        PagedResultOfAdminQuestionDto: {
            items: components["schemas"]["AdminQuestionDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        PagedResultOfAdminUserDto: {
            items: components["schemas"]["AdminUserDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        /** @enum {unknown} */
        PracticeMode: "Practice" | "Challenge" | "Random" | "Adaptive" | "DailyChallenge" | "Roadmap";
        PracticeSessionDto: {
            /** Format: uuid */
            id: string;
            mode: components["schemas"]["PracticeMode"];
            topicSlug: null | string;
            topicName: null | string;
            subtopicSlug: null | string;
            subtopicName: null | string;
            difficulty: null | components["schemas"]["Difficulty"];
            /** Format: uuid */
            roadmapStepId: null | string;
            isDailyChallenge: boolean;
            /** Format: int32 */
            totalQuestions: number;
            /** Format: int32 */
            answeredCount: number;
            /** Format: int32 */
            correctCount: number;
            /** Format: int32 */
            xpEarned: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: null | string;
            questions: components["schemas"]["SessionQuestionDto"][];
        };
        ProfileDto: {
            user: components["schemas"]["UserSummaryDto"];
            topicProgress: components["schemas"]["TopicProgressDto"][];
            accuracyByDifficulty: components["schemas"]["DifficultyBreakdownDto"][];
            achievements: components["schemas"]["AchievementDto"][];
            roadmaps: components["schemas"]["RoadmapProgressSummaryDto"][];
            strongestTopics: components["schemas"]["TopicProgressDto"][];
            weakestTopics: components["schemas"]["TopicProgressDto"][];
            activity: components["schemas"]["DailyActivityDto"][];
        };
        /** @enum {unknown} */
        QuestionType: "MultipleChoice" | "MultipleSelect" | "TrueFalse" | "CodingChallenge" | "CodeOutput" | "Debugging" | "ArchitectureScenario";
        RecommendationDto: {
            kind: string;
            title: string;
            reason: string;
            topicSlug: string;
            subtopicSlug: null | string;
            difficulty: null | string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            username: string;
            displayName: null | string;
        };
        ResetPasswordRequest: {
            email: string;
            resetCode: string;
            newPassword: string;
        };
        RoadmapDetailDto: {
            summary: components["schemas"]["RoadmapSummaryDto"];
            prerequisites: components["schemas"]["RoadmapPrerequisiteDto"][];
            modules: components["schemas"]["RoadmapModuleDto"][];
            /** Format: uuid */
            currentStepId: null | string;
        };
        /** @enum {unknown} */
        RoadmapDifficulty: "Beginner" | "Intermediate" | "Advanced" | "Expert";
        RoadmapModuleDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: int32 */
            order: number;
            /** Format: int32 */
            xpReward: number;
            isCompleted: boolean;
            steps: components["schemas"]["RoadmapStepDto"][];
        };
        RoadmapPrerequisiteDto: {
            slug: string;
            name: string;
            /** Format: int32 */
            minimumPercent: number;
            /** Format: double */
            currentPercent: number;
            isMet: boolean;
        };
        RoadmapProgressSummaryDto: {
            slug: string;
            name: string;
            icon: string;
            category: string;
            /** Format: int32 */
            completedSteps: number;
            /** Format: int32 */
            stepsCount: number;
            /** Format: double */
            percentComplete: number;
            currentStepTitle: null | string;
            /** Format: uuid */
            currentStepId: null | string;
            isCompleted: boolean;
            /** Format: date-time */
            lastActivityAt: string;
        };
        RoadmapStepDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            order: number;
            difficulty: string;
            /** Format: int32 */
            estimatedMinutes: number;
            topicSlug: string;
            topicName: string;
            subtopicSlug: null | string;
            subtopicName: null | string;
            /** Format: int32 */
            minimumQuestions: number;
            /** Format: int32 */
            minimumAccuracy: number;
            /** Format: int32 */
            xpReward: number;
            status: string;
            criteria: null | components["schemas"]["StepCriteriaResult"];
        };
        RoadmapSummaryDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: string;
            /** Format: int32 */
            estimatedHours: number;
            /** Format: int32 */
            stepsCount: number;
            /** Format: int32 */
            modulesCount: number;
            icon: string;
            /** Format: int32 */
            xpReward: number;
            prerequisites: string[];
            progress: null | components["schemas"]["RoadmapUserStateDto"];
        };
        RoadmapUserStateDto: {
            isUnlocked: boolean;
            isStarted: boolean;
            isCompleted: boolean;
            /** Format: int32 */
            completedSteps: number;
            /** Format: double */
            percentComplete: number;
            /** Format: date-time */
            lastActivityAt: null | string;
        };
        SearchResultDto: {
            type: string;
            slug: string;
            title: string;
            subtitle: string;
            icon: string;
            url: string;
        };
        SessionProgressDto: {
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            correct: number;
            /** Format: int32 */
            xpEarned: number;
            isComplete: boolean;
        };
        SessionQuestionDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            index: number;
            topicSlug: string;
            topicName: string;
            subtopicSlug: string;
            subtopicName: string;
            difficulty: components["schemas"]["Difficulty"];
            title: string;
            questionText: string;
            /** Format: int32 */
            xpReward: number;
            options: components["schemas"]["OptionDto"][];
            answer: null | components["schemas"]["AnswerFeedbackDto"];
        };
        StartPracticeRequest: {
            mode?: components["schemas"]["PracticeMode"];
            topicSlug?: null | string;
            subtopicSlug?: null | string;
            difficulty?: null | components["schemas"]["Difficulty"];
            /** Format: int32 */
            count?: null | number;
            /** Format: uuid */
            roadmapStepId?: null | string;
        };
        StepCriteriaResult: {
            /** Format: int32 */
            answeredQuestions: number;
            /** Format: int32 */
            correctQuestions: number;
            /** Format: double */
            accuracy: number;
            /** Format: int32 */
            requiredQuestions: number;
            /** Format: int32 */
            requiredAccuracy: number;
            isMet: boolean;
        };
        SubmitAnswerRequest: {
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            selectedOptionId: string;
            /** Format: int32 */
            timeSpentSeconds: number;
        };
        SubtopicAccuracyDto: {
            topicSlug: string;
            slug: string;
            name: string;
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: double */
            accuracy: number;
        };
        SubtopicDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** Format: int32 */
            order: number;
            /** Format: int32 */
            questionCount: number;
        };
        SubtopicProgressDto: {
            slug: string;
            name: string;
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: double */
            accuracy: number;
        };
        TopicAccuracyDto: {
            slug: string;
            name: string;
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: double */
            accuracy: number;
        };
        TopicDetailDto: {
            topic: components["schemas"]["TopicDto"];
            progress: null | components["schemas"]["TopicProgressDto"];
            subtopicProgress: components["schemas"]["SubtopicProgressDto"][];
            byDifficulty: components["schemas"]["DifficultyBreakdownDto"][];
        };
        TopicDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            icon: string;
            /** Format: int32 */
            order: number;
            questions: components["schemas"]["DifficultyCountsDto"];
            subtopics: components["schemas"]["SubtopicDto"][];
        };
        TopicProgressDto: {
            topicSlug: string;
            topicName: string;
            icon: string;
            category: string;
            level: components["schemas"]["LevelDto"];
            /** Format: int32 */
            questionsAnswered: number;
            /** Format: int32 */
            correctAnswers: number;
            /** Format: double */
            accuracy: number;
            /** Format: int32 */
            totalQuestions: number;
            /** Format: int32 */
            distinctAnswered: number;
            /** Format: double */
            completionPercent: number;
            /** Format: date-time */
            lastActivityAt: null | string;
        };
        UpdateProfileRequest: {
            displayName: null | string;
            bio: null | string;
            avatarUrl: null | string;
        };
        UserSummaryDto: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            email: string;
            avatarUrl: null | string;
            bio: null | string;
            isAdmin: boolean;
            level: components["schemas"]["LevelDto"];
            /** Format: int32 */
            currentStreak: number;
            /** Format: int32 */
            longestStreak: number;
            /** Format: int32 */
            questionsAnswered: number;
            /** Format: int32 */
            correctAnswers: number;
            /** Format: double */
            accuracy: number;
            /** Format: int32 */
            globalRank: number;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
