"""Source of truth for the TechRat knowledge tree.

Run `python3 scripts/seed-src/topics.py` to regenerate
backend/TechRat.Infrastructure/Seed/Data/topics.json.
Format of each subtopic: "slug|Display Name".
"""
import json, os

TOPICS = [
    # slug, name, category, icon, description, subtopics
    ("programming-fundamentals", "Programming Fundamentals", "Computer Science", "code",
     "Variables, types, control flow, functions, memory and complexity — the base of everything.",
     ["variables-types|Variables & Types", "control-flow|Control Flow", "functions|Functions", "recursion|Recursion",
      "memory-pointers|Memory & Pointers", "complexity-big-o|Complexity & Big O", "boolean-logic|Boolean Logic",
      "number-systems|Binary & Hexadecimal", "computer-architecture|Computer Architecture", "discrete-math|Discrete Math",
      "problem-solving|Problem Solving"]),
    ("data-structures", "Data Structures", "Computer Science", "boxes",
     "Arrays, lists, hash tables, trees, heaps, graphs and more.",
     ["arrays|Arrays", "strings|Strings", "linked-lists|Linked Lists", "stacks|Stacks", "queues|Queues",
      "hash-tables|Hash Tables & Sets", "trees|Trees & Binary Trees", "binary-search-trees|Binary Search Trees",
      "heaps|Heaps & Priority Queues", "graphs|Graphs", "tries|Tries", "disjoint-set|Disjoint Set", "matrices|Matrices"]),
    ("algorithms", "Algorithms", "Computer Science", "git-branch",
     "Sorting, searching, graph algorithms, dynamic programming and classic interview patterns.",
     ["sorting|Sorting", "binary-search|Searching & Binary Search", "two-pointers|Two Pointers",
      "sliding-window|Sliding Window", "prefix-sum|Prefix Sum", "backtracking|Recursion & Backtracking",
      "divide-and-conquer|Divide and Conquer", "greedy|Greedy", "dynamic-programming|Dynamic Programming",
      "graph-traversal|BFS & DFS", "topological-sort|Topological Sort", "shortest-paths|Shortest Paths",
      "union-find|Union Find", "intervals|Intervals", "tree-traversal|Tree Traversal", "string-algorithms|String Algorithms"]),
    ("system-design", "System Design", "Architecture", "server",
     "From client-server basics to multi-region, fault-tolerant distributed systems.",
     ["fundamentals|Client-Server, DNS & APIs", "scaling|Vertical & Horizontal Scaling", "caching|Caching & Redis",
      "cdn|CDN", "load-balancing|Load Balancing", "replication-partitioning|Replication, Partitioning & Sharding",
      "messaging|Queues & Message Brokers", "rate-limiting|Rate Limiting", "api-gateway|API Gateway & Service Discovery",
      "resilience|Circuit Breaker, Retry, Backoff & Bulkhead", "idempotency|Idempotency",
      "consistency|Consistency, CAP & Consensus", "distributed-transactions|Sagas & Outbox",
      "event-driven|Event Driven Architecture", "high-availability|High Availability & Disaster Recovery",
      "interview-scenarios|Interview Scenarios"]),
    ("backend-engineering", "Backend Engineering", "Engineering", "database-zap",
     "HTTP, REST, API design, authentication, realtime, background jobs and webhooks.",
     ["http-rest|HTTP & REST", "api-design|API Design, Pagination & Versioning", "auth|Sessions, Cookies, OAuth & JWT",
      "realtime|WebSockets & SSE", "grpc|gRPC", "background-jobs|Background Jobs, Workers & Queues",
      "webhooks|Webhooks", "backend-caching|Caching & Idempotent APIs"]),
    ("databases", "Databases", "Data", "database",
     "SQL, transactions, indexing, concurrency, scaling and NoSQL.",
     ["sql-basics|SQL Basics", "joins|Joins", "aggregation|GROUP BY & HAVING", "advanced-sql|Subqueries, CTEs & Window Functions",
      "transactions|Transactions & ACID", "concurrency|Isolation, Locking & MVCC", "indexing|Indexes & Query Plans",
      "data-modeling|Normalization & Constraints", "scaling-databases|Replication, Sharding & Pooling",
      "nosql|NoSQL, Redis & MongoDB"]),
    ("csharp", "C#", "Languages", "hash",
     "The C# language from syntax to async, concurrency, memory and performance.",
     ["language-basics|Syntax, Types, Structs & Records", "oop|Classes, Interfaces & Polymorphism", "generics|Generics",
      "delegates-events|Delegates & Events", "linq|LINQ", "exceptions-nullability|Exceptions & Nullable References",
      "collections|Collections", "memory-gc|Memory, GC & IDisposable", "async-await|Async & Await",
      "concurrency|Threads, Locks & Concurrent Collections", "reflection-attributes|Reflection & Attributes",
      "performance|Span & Performance"]),
    ("dotnet", ".NET", "Frameworks", "layers",
     "CLR, dependency injection, ASP.NET Core, EF Core and testing.",
     ["runtime|CLR, JIT & GC", "dependency-injection|Dependency Injection", "configuration|Configuration, Options & Logging",
      "aspnetcore|ASP.NET Core, Middleware & Routing", "aspnetcore-security|Authentication & Authorization",
      "hosting|BackgroundService & Health Checks", "ef-core|EF Core Fundamentals", "ef-core-performance|EF Core Performance & Concurrency",
      "testing-dotnet|Testing .NET"]),
    ("javascript", "JavaScript", "Languages", "braces",
     "Types, scope, closures, prototypes, async and the event loop.",
     ["types|Types & Coercion", "scope-closures|Scope & Closures", "objects-prototypes|Objects, Prototypes & Classes",
      "functions-this|Functions & this", "async|Promises, Async & Event Loop", "modules|Modules",
      "dom-browser|DOM & Fetch", "errors|Errors", "performance-memory|Memory & Performance"]),
    ("typescript", "TypeScript", "Languages", "file-type",
     "Static types for JavaScript: generics, narrowing, utility and advanced types.",
     ["basic-types|Primitive Types & Inference", "interfaces-types|Interfaces vs Types", "generics|Generics",
      "unions-narrowing|Unions, Intersections & Narrowing", "utility-types|Utility Types", "enums-modules|Enums & Modules",
      "advanced-types|Advanced Types"]),
    ("frontend", "Frontend Engineering", "Engineering", "layout",
     "HTML, CSS, accessibility, browser fundamentals, performance and architecture.",
     ["html-semantics|Semantic HTML", "accessibility|Accessibility", "css-layout|CSS, Flexbox & Grid",
      "responsive-design|Responsive Design", "browser-fundamentals|Browser Rendering", "web-performance|Web Performance",
      "frontend-architecture|Frontend Architecture & State", "forms-validation|Forms & Validation",
      "web-security|Frontend Security"]),
    ("react", "React", "Frameworks", "atom",
     "Components, hooks, rendering, data fetching and testing.",
     ["components-jsx|Components & JSX", "props-state|Props, State & Events", "hooks|useState & useEffect",
      "memoization|useMemo, useCallback & memo", "refs-context|useRef & Context", "custom-hooks|Custom Hooks",
      "rendering|Rendering & Reconciliation", "data-fetching|Data Fetching & React Query",
      "routing-forms|Routing & Forms", "error-boundaries|Error Boundaries", "testing-react|Testing React"]),
    ("python", "Python", "Languages", "terminal",
     "Pythonic code: collections, decorators, generators, typing and asyncio.",
     ["syntax-collections|Syntax & Collections", "functions-decorators|Functions & Decorators",
      "iterators-generators|Iterators & Generators", "classes|Classes", "exceptions-context|Exceptions & Context Managers",
      "modules-venv|Modules & Virtual Environments", "typing|Typing", "asyncio-concurrency|AsyncIO & Concurrency",
      "testing-python|Testing", "performance-python|Performance"]),
    ("java", "Java", "Languages", "coffee",
     "JVM, collections, streams, concurrency and Spring fundamentals.",
     ["language-basics|Language Basics", "jvm|JVM", "oop-java|Classes & Interfaces", "generics-collections|Generics & Collections", "streams|Streams",
      "exceptions-java|Exceptions", "concurrency-java|Threads & Concurrency", "gc-java|Garbage Collection",
      "spring|Spring, REST & DI"]),
    ("git", "Git", "Tools", "git-merge",
     "Commits, branches, merging, rebasing and team workflows.",
     ["basics|Repositories & Commits", "branching-merging|Branches, Merges & Conflicts", "rebase|Rebase",
      "remotes|Fetch, Pull & Push", "undoing|Reset & Revert", "advanced|Cherry Pick, Stash & Tags",
      "workflows|Workflows, Pull Requests & Code Review"]),
    ("operating-systems", "Operating Systems", "Computer Science", "cpu",
     "Processes, threads, scheduling, memory, file systems and synchronization.",
     ["processes-threads|Processes & Threads", "scheduling|Scheduling & Context Switching",
      "memory-management|Virtual Memory, Paging, Stack & Heap", "file-systems|File Systems",
      "system-calls-io|System Calls & I/O", "synchronization|Locks, Semaphores & Deadlocks"]),
    ("networking", "Computer Networking", "Computer Science", "network",
     "OSI, TCP/IP, DNS, HTTP, TLS, proxies and load balancing.",
     ["models|OSI & TCP/IP Models", "ip-subnetting|IP & Subnetting", "tcp-udp|TCP, UDP, Ports & Sockets", "dns|DNS",
      "http-https|HTTP & HTTPS", "tls|TLS & Certificates", "proxies-load-balancing|Proxies & Load Balancing",
      "nat-firewall|NAT & Firewalls", "cdn-websocket|CDN & WebSocket"]),
    ("security", "Security", "Security", "shield",
     "Authentication, authorization, OWASP Top 10, threat modeling and secure coding.",
     ["passwords-authentication|Passwords, Hashing & MFA", "authorization|Authorization, RBAC & ABAC",
      "oauth-oidc-jwt|OAuth, OIDC & JWT", "injection|SQL, Command Injection & Path Traversal", "xss-csrf|XSS & CSRF",
      "ssrf|SSRF", "cors-headers-tls|CORS, Security Headers & TLS", "secrets|Secrets & Least Privilege",
      "owasp-threat-modeling|OWASP Top 10 & Threat Modeling", "secure-coding|Secure Coding"]),
    ("testing", "Testing & Quality", "Engineering", "flask-conical",
     "Unit, integration and E2E tests, test doubles, TDD and performance testing.",
     ["unit-testing|Unit Testing & AAA", "test-doubles|Mocks, Stubs & Fakes", "integration-e2e|Integration & E2E Testing",
      "tdd-pyramid|TDD & Test Pyramid", "test-design|Boundary, Negative & Regression Testing",
      "advanced-testing|Property, Mutation & Contract Testing", "performance-testing|Load & Stress Testing",
      # TDD in depth (junior interview and first-job roadmaps)
      "tdd-red-green-refactor|Red, Green, Refactor", "tdd-test-first-design|Test-First Design",
      "tdd-kata-walkthroughs|TDD Kata Walkthroughs", "tdd-outside-in|Outside-In TDD & Test Doubles",
      "tdd-bug-fixing|Bug Fixes & Safe Refactoring with TDD", "tdd-legacy-seams|Legacy Code, Seams & Characterization Tests",
      "tdd-pitfalls|TDD Pitfalls & Design Feedback"]),
    ("clean-code", "Clean Code & Software Design", "Engineering", "sparkles",
     "Clean code, SOLID, coupling and cohesion, refactoring and domain modeling.",
     ["clean-code|Clean Code", "solid|SOLID", "principles|DRY, KISS & YAGNI", "coupling-cohesion|Coupling, Cohesion & Composition",
      "refactoring|Refactoring & Code Smells", "domain-modeling|Domain Modeling",
      # SOLID in depth (junior interview and first-job roadmaps)
      "solid-srp-ocp|Single Responsibility & Open/Closed", "solid-lsp-isp|Liskov Substitution & Interface Segregation",
      "solid-dip-di|Dependency Inversion & Injection", "solid-violations|Spotting SOLID Violations"]),
    ("design-patterns", "Design Patterns", "Engineering", "puzzle",
     "Creational, structural, behavioral and data-access patterns.",
     ["creational|Factory, Builder & Singleton", "structural|Adapter, Decorator, Proxy & Facade",
      "behavioral|Strategy, Observer, Command & Chain", "mediator-template|Mediator & Template Method",
      "data-access|Repository & Unit of Work"]),
    ("software-architecture", "Software Architecture", "Architecture", "building",
     "Layered, clean, hexagonal, modular monolith, microservices, DDD and more.",
     ["layered|Layered Architecture", "clean-hexagonal|Clean, Hexagonal & Onion", "modular-monolith|Modular Monolith",
      "microservices|Microservices", "event-driven-architecture|Event Driven Architecture", "serverless|Serverless",
      "ddd|Domain Driven Design", "api-gateway-bff|API Gateway & BFF", "cqrs-event-sourcing|CQRS & Event Sourcing"]),
    ("devops", "DevOps", "Cloud & DevOps", "infinity",
     "Linux, CI/CD, artifacts, infrastructure as code and deployment strategies.",
     ["linux-shell|Linux & Shell", "ci-cd|CI & CD", "build-artifacts|Builds & Artifacts", "iac|Infrastructure as Code & Terraform",
      "configuration-secrets|Configuration & Secrets", "deployment-strategies|Blue/Green, Canary, Rollback & Feature Flags"]),
    ("docker", "Docker", "Cloud & DevOps", "container",
     "Images, containers, Dockerfiles, volumes, networks and Compose.",
     ["images-layers|Images, Layers & Build Cache", "containers|Containers", "dockerfile|Dockerfile & Multi-Stage Builds",
      "volumes-networks|Volumes, Networks & Ports", "compose|Docker Compose", "registries|Registries",
      "docker-security|Security & Resource Limits"]),
    ("kubernetes", "Kubernetes", "Cloud & DevOps", "ship-wheel",
     "Pods, deployments, services, config, storage, probes and autoscaling.",
     ["architecture|Cluster, Nodes & Namespaces", "workloads|Pods, Deployments & ReplicaSets",
      "services-networking|Services, Ingress & Gateway", "config-secrets|ConfigMaps & Secrets", "storage|Volumes & Persistent Volumes",
      "probes|Readiness, Liveness & Startup Probes", "resources-autoscaling|Requests, Limits & Autoscaling",
      "rollouts|Rolling Updates"]),
    ("cloud", "Cloud Engineering", "Cloud & DevOps", "cloud",
     "Provider-agnostic cloud concepts plus AWS and Google Cloud fundamentals.",
     ["service-models|IaaS, PaaS & SaaS", "compute|Compute, Containers & Serverless", "storage-databases|Storage & Databases",
      "cloud-networking|Networking, Load Balancing & Autoscaling", "identity-secrets|Identity & Secrets",
      "regions-dr|Regions, Availability Zones & DR", "monitoring|Monitoring", "aws|AWS Fundamentals", "gcp|Google Cloud Fundamentals"]),
    ("azure", "Azure", "Cloud & DevOps", "cloud-cog",
     "App Service, Container Apps, Functions, AKS, data, messaging, networking and monitoring.",
     ["compute|App Service, Container Apps, Functions & AKS", "data|Azure SQL, PostgreSQL & Blob Storage",
      "identity-security|Key Vault & Managed Identity", "messaging|Service Bus & Event Grid",
      "networking|VNet, Load Balancer, App Gateway & Front Door", "monitoring|Azure Monitor & Application Insights"]),
    ("ai-engineering", "AI Engineering", "AI & Data", "brain-circuit",
     "LLMs, prompting, tool calling, embeddings, RAG, agents, evaluation and AI security.",
     ["ai-fundamentals|AI, Neural Networks & Transformers", "llm-fundamentals|LLMs, Tokens & Context Windows",
      "prompt-engineering|Prompt Engineering & Structured Outputs", "tool-calling|Function & Tool Calling",
      "embeddings-vector-search|Embeddings & Vector Search", "rag|RAG, Chunking & Reranking",
      "agents|Agents, Memory & MCP", "evaluation|Evaluation & Hallucination", "ai-security|Prompt Injection & Guardrails",
      "llm-ops|Latency, Cost, Routing & Observability"]),
    ("machine-learning", "Machine Learning", "AI & Data", "chart-scatter",
     "Supervised and unsupervised learning, validation, metrics and models.",
     ["ml-fundamentals|Supervised & Unsupervised Learning", "validation|Training, Validation & Cross Validation",
      "metrics|Precision, Recall, F1 & ROC", "bias-variance|Bias, Variance & Regularization",
      "regression-classification|Regression & Classification", "clustering-pca|Clustering & PCA",
      "trees-ensembles|Decision Trees, Random Forest & Boosting", "feature-engineering|Feature Engineering",
      "neural-networks|Neural Networks"]),
    ("data-engineering", "Data Engineering", "AI & Data", "workflow",
     "Pipelines, batch and streaming, warehouses and lakes, Kafka and data quality.",
     ["etl-elt|ETL, ELT & Pipelines", "batch-streaming|Batch & Streaming", "storage-architectures|Warehouse, Lake & Lakehouse",
      "kafka|Kafka", "schema-quality|Schema Evolution & Data Quality", "formats-partitioning|Parquet & Partitioning",
      "orchestration|Orchestration"]),
    ("observability", "Observability", "Cloud & DevOps", "activity",
     "Logs, metrics, traces, OpenTelemetry, SLOs and incident investigation.",
     ["logging|Structured Logging", "metrics|Metrics & Golden Signals", "tracing|Distributed Tracing & OpenTelemetry",
      "slo|SLI, SLO, SLA & Error Budgets", "alerting-incidents|Alerting, Dashboards & Incidents"]),
    ("performance", "Performance Engineering", "Engineering", "gauge",
     "Latency, throughput, profiling, allocations, database tuning, caching and load testing.",
     ["fundamentals|Latency, Throughput, CPU, Memory & I/O", "profiling-benchmarking|Profiling & Benchmarking",
      "memory-allocations|GC & Allocations", "database-performance|N+1, Indexes & Connection Pooling",
      "caching-batching|Caching, Batching & Compression", "load-testing|Load & Stress Testing",
      # Backend performance best-practices pack (scenario-heavy, own scopes so they never overlap the basics above)
      "bp-api-latency|API Latency Budgets & Hot Paths", "bp-data-access|Data Access Patterns at Scale",
      "bp-caching-strategy|Caching Strategy & Invalidation", "bp-async-concurrency|Async I/O, Concurrency & Backpressure",
      "bp-payloads-network|Payloads, Compression & Network Round Trips"]),
    ("engineering-leadership", "Engineering Leadership", "Career", "users",
     "Code review, technical decisions, incidents, mentoring and architecture communication.",
     ["code-review|Code Review", "technical-decisions|Technical Decisions & Tradeoffs", "incident-handling|Incident Handling",
      "reliability|Reliability Practices", "mentoring|Mentoring", "communication|Architecture Communication & Leadership"]),
    # ---- Added with the module catalog (ADR-0012) -------------------------------------------------
    ("statistics", "Statistics", "AI & Data", "sigma",
     "Descriptive statistics, probability, distributions, sampling and inference for data work.",
     ["descriptive-statistics|Descriptive Statistics", "probability|Probability", "distributions|Distributions",
      "sampling|Sampling & Bias", "hypothesis-testing|Hypothesis Testing", "confidence-intervals|Confidence Intervals",
      "correlation-causation|Correlation vs Causation", "ab-testing|A/B Testing", "regression-basics|Regression Basics"]),
    ("data-analysis-python", "Data Analysis with Python", "AI & Data", "table",
     "NumPy and pandas for cleaning, joining, aggregating and visualising data in notebooks.",
     ["numpy|NumPy", "pandas-fundamentals|pandas Fundamentals", "data-cleaning|Data Cleaning", "merge-join|Merge & Join",
      "groupby-aggregation|GroupBy & Aggregation", "time-series|Time Series", "visualization|Visualization with Matplotlib & Seaborn",
      "notebooks|Notebooks & Reproducibility"]),
    ("data-visualization-bi", "Data Visualization & BI", "AI & Data", "bar-chart-3",
     "Choosing charts, building dashboards, KPIs, storytelling and modeling data for BI tools.",
     ["chart-selection|Choosing the Right Chart", "dashboards|Dashboards", "storytelling|Data Storytelling", "kpis|KPIs & Metrics",
      "bi-tools|Power BI, Tableau & Looker Concepts", "bi-data-modeling|Data Modeling for BI"]),
    ("spreadsheets", "Spreadsheets", "AI & Data", "sheet",
     "Formulas, lookups, pivot tables, validation and cleaning in Excel and Google Sheets.",
     ["formulas|Formulas & References", "lookups|Lookup Functions", "pivot-tables|Pivot Tables", "data-validation|Data Validation",
      "sheet-cleaning|Cleaning Data in Sheets", "sheet-charts|Charts in Spreadsheets"]),
    ("ai-assisted-development", "AI-Assisted Development", "AI & Data", "bot",
     "Working with coding agents such as Claude Code: context, prompting, tools, automation, review and safety.",
     ["coding-agents|Coding Agents", "context-instructions|Context & Instruction Files", "prompting-for-code|Prompting for Code",
      "tools-mcp|Tools & MCP", "subagents-parallel|Subagents & Parallel Work", "hooks-automation|Hooks & Automation",
      "reviewing-ai-code|Reviewing & Testing AI-Generated Code", "agent-security|Security & Permissions",
      "cost-latency|Cost & Latency", "agents-in-ci|Agent Workflows in CI"]),
    ("cpp", "C++", "Languages", "cpu",
     "Modern C++: types, memory and RAII, templates, the STL, move semantics, concurrency and tooling.",
     ["syntax-types|Syntax & Types", "pointers-references|Pointers & References", "memory-raii|Memory & RAII",
      "smart-pointers|Smart Pointers", "classes-oop|Classes & OOP", "templates|Templates", "stl|STL Containers & Algorithms",
      "move-semantics|Move Semantics", "concurrency-cpp|Concurrency", "build-cmake|Build Systems & CMake",
      "undefined-behavior|Undefined Behavior", "modern-cpp|Modern C++ (17/20/23)"]),
    ("aws", "AWS", "Cloud & DevOps", "cloud",
     "Core AWS services and the Well-Architected way of running them: IAM, networking, compute, storage, data, cost and resilience.",
     ["iam|IAM & Least Privilege", "vpc|VPC & Networking", "compute|EC2, ECS, EKS & Lambda", "s3|S3", "databases|RDS & DynamoDB",
      "cloudwatch|CloudWatch", "well-architected|Well-Architected Framework", "cost-optimization|Cost Optimization",
      "security-best-practices|Security Best Practices", "reliability-best-practices|Reliability, Backup & DR"]),
    ("offensive-defensive-security", "Offensive & Defensive Security", "Security", "shield-alert",
     "Security operations, incident response, vulnerability management and how attacks work, from a defender's point of view.",
     ["security-operations|Security Operations & SOC", "incident-response|Incident Response", "forensics|Forensics Basics",
      "vulnerability-management|Vulnerability Management", "pentest-methodology|Pentest Methodology (Ethical)",
      "malware|Malware Types", "zero-trust|IAM & Zero Trust", "cloud-security|Cloud Security",
      "cryptography|Cryptography Basics", "compliance|Compliance Frameworks"]),
    ("api-security", "API Security", "Security", "lock",
     "Securing APIs end to end: authentication, object- and function-level authorization, input, limits, transport and monitoring.",
     ["api-authentication|API Authentication & Tokens", "object-function-authz|BOLA & BFLA (Authorization)",
      "input-validation|Input Validation & Mass Assignment", "rate-limiting-abuse|Rate Limiting & Abuse",
      "transport-cors-secrets|TLS, CORS & Secrets", "logging-monitoring|API Logging & Monitoring",
      "owasp-api-top10|OWASP API Security Top 10"]),
    ("code-review", "Code Review", "Engineering", "git-pull-request",
     "Reviewing code effectively: goals, PR size, what to look for, feedback and automation.",
     ["review-goals|Goals of Code Review", "pr-size|PR Size & Scope", "review-correctness-design|Reviewing Correctness & Design",
      "review-tests-security|Reviewing Tests & Security", "review-feedback|Giving & Receiving Feedback",
      "review-automation|Automation, Linters & Checklists"]),
    ("junior-career", "Junior Career & Interviews", "Career", "rocket",
     "Behavioral and technical interviews for a first job, the first 90 days at work and pull requests for newcomers.",
     ["star-method|STAR Method", "common-behavioral-questions|Common Behavioral Questions",
      "mistakes-and-not-knowing|Mistakes & Not Knowing the Answer", "offers-and-negotiation|Offers & Negotiation",
      "junior-oop-concepts|OOP & Design Interview Questions", "junior-web-db-concepts|Web, API & Database Interview Questions",
      "live-coding-communication|Live Coding & Thinking Aloud",
      "onboarding-first-weeks|Onboarding & First Weeks", "reading-codebases|Reading an Unfamiliar Codebase",
      "asking-for-help|Asking for Help & Learning on the Job", "feedback-and-growth|Feedback & Growth Plan",
      "small-pull-requests|Small, Clear Pull Requests", "receiving-review-feedback|Receiving Review Feedback",
      "reviewing-as-a-junior|Reviewing as a Junior"]),
    ("capstones", "Capstones", "Career", "trophy",
     "Mixed-topic, scenario-based final challenges for roadmaps.",
     ["data-analyst|Data Analyst Capstone", "ai-data-scientist|AI & Data Scientist Capstone",
      "ai-assisted-development|AI-Assisted Development Capstone", "cyber-security|Cyber Security Capstone", "cpp|C++ Capstone"]),
]

out = []
for i, (slug, name, cat, icon, desc, subs) in enumerate(TOPICS):
    out.append({
        "slug": slug, "name": name, "category": cat, "icon": icon, "description": desc, "order": i + 1,
        "subtopics": [{"slug": s.split("|")[0], "name": s.split("|")[1], "order": j + 1} for j, s in enumerate(subs)],
    })

path = os.path.join(os.path.dirname(__file__), "../../backend/TechRat.Infrastructure/Seed/Data/topics.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2)
print(len(out), "topics,", sum(len(t["subtopics"]) for t in out), "subtopics")
